version: '3'

vars:
  REPO_DIR: '{{.TASKFILE_DIR}}'

tasks:
  install:
    desc: Symlink config files into ~/.cursor and set up cli-config
    cmds:
      - mkdir -p $HOME/.cursor
      - ln -sf {{.REPO_DIR}}/agent.json $HOME/.cursor/agent.json
      - |
        if [ ! -f $HOME/.cursor/cli-config.json ]; then
          cp {{.REPO_DIR}}/cli-config.example.json $HOME/.cursor/cli-config.json
          echo "Created $HOME/.cursor/cli-config.json"
        else
          echo "$HOME/.cursor/cli-config.json exists, skipping"
        fi
      - |
        if [ ! -f $HOME/.cursor/mcp.json ]; then
          cp {{.REPO_DIR}}/mcp.example.json $HOME/.cursor/mcp.json
          echo "Created $HOME/.cursor/mcp.json from template (set GITHUB_TOKEN etc.)"
        else
          echo "$HOME/.cursor/mcp.json exists, skipping"
        fi
      - echo "Run 'cursor-agent login' to authenticate, then 'cursor-agent about' to validate"

  validate:
    desc: Cursor-agent evaluates its own outputs against config rules
    env:
      CURSOR_VALIDATE_USE_CACHED: "1"
    cmds:
      - chmod +x {{.REPO_DIR}}/scripts/validate.sh
      - bash {{.REPO_DIR}}/scripts/validate.sh

  validate:live:
    desc: Run all prompts live, then cursor-agent evaluates (4 API calls, ~5-10 min)
    env:
      CURSOR_VALIDATE_USE_CACHED: "0"
    cmds:
      - bash {{.REPO_DIR}}/scripts/validate.sh

  validate:quick:
    desc: Use cached outputs + injected PASS verdict (no API calls)
    env:
      CURSOR_VALIDATE_USE_CACHED: "1"
      CURSOR_VERDICT: |
        minimal: PASS
        antihallucination: PASS
        controlflow: PASS
        OVERALL: PASS
    cmds:
      - bash {{.REPO_DIR}}/scripts/validate.sh
